name: Main build

on:
  push:
    branches:
      - main
      - develop

jobs:
  main:
    name: Main build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - name: Add pub cache to path
        shell: bash
        run: |
          echo "export PATH=$PATH:$HOME/.pub-cache/bin" >> $GITHUB_PATH


      - name: Install project dependencies
        run: |
          dart pub global activate melos

      - name: Flutter get
        run: melos run get
