name: Main build

on:
  push:
    branches:
      - main
      - develop

jobs:
  docs:
    name: Build & deploy docs
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - name: Add pub cache to path
        shell: bash
        run: |
          echo "export PATH=$PATH:$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install project dependencies
        run: |
          dart pub global activate melos
          dart pub global activate dartdoc

      - name: Flutter get
        run: melos run get

      - name: Build docs
        run: melos run docs

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true

  web:
    name: Build & deploy web
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - name: Add pub cache to path
        shell: bash
        run: |
          echo "export PATH=$PATH:$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install project dependencies
        run: |
          dart pub global activate melos

      - name: Flutter get
        run: melos run get

      - name: Build web
        run: melos run build:web && melos run stage:web

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
